import { useEffect, useRef } from 'react';
import gsap from 'gsap'; import { ScrollTrigger } from 'gsap/ScrollTrigger'; import Lenis from 'lenis';
gsap.registerPlugin(ScrollTrigger);
const missions=[['01','COMPETE','Push the limits. Build what the world has never seen.'],['02','LEARN','Meet the minds shaping tomorrow and take their knowledge further.'],['03','CONNECT','Find your people. Ideas get louder when we build together.']];
const events=[['ROBO WARS','Engineering / Arena','Battle-ready machines. One arena. Zero compromises.'],['EUREKA!','Innovation / Pitch','Turn the spark of an idea into something the world can use.'],['IITB TECH','Hackathon / 36 HRS','A problem. A team. A weekend to change the possible.']];
const stats=[['28','YEARS OF MAKING'],['100K+','ANNUAL VISITORS'],['500+','EVENTS & CHALLENGES'],['01','UNSTOPPABLE COMMUNITY']];
function App(){const root=useRef<HTMLDivElement>(null); useEffect(()=>{const lenis=new Lenis({duration:1.2}); const raf=(t:number)=>{lenis.raf(t);requestAnimationFrame(raf)}; requestAnimationFrame(raf); const ctx=gsap.context(()=>{gsap.from('.hero-line',{y:120,opacity:0,duration:1.2,stagger:.12,ease:'power4.out'}); gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:50,opacity:0,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 84%'}})); gsap.to('.hero-image',{yPercent:16,ease:'none',scrollTrigger:{trigger:'.hero',scrub:true}}); gsap.utils.toArray<HTMLElement>('.stat-number').forEach(el=>{const end=el.dataset.value||'0'; ScrollTrigger.create({trigger:el,start:'top 90%',once:true,onEnter:()=>{gsap.fromTo(el,{innerText:'0'},{innerText:end,duration:1.5,snap:{innerText:1}})}})}); return ()=>lenis.destroy()},root); return()=>ctx.revert()},[]); return <div ref={root}>
<nav><a className="brand" href="#top">TECHFEST<span> / IIT BOMBAY</span></a><div className="nav-links"><a href="#about">ABOUT</a><a href="#missions">MISSIONS</a><a href="#events">EVENTS</a></div><a className="nav-cta" href="#enter">ENTER <span>↗</span></a></nav>
<main id="top"><section className="hero"><div className="hero-image"/><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow hero-line">IIT BOMBAY · 28TH EDITION</p><h1><span className="hero-line">THE FUTURE</span><span className="hero-line accent">IS BUILT</span><span className="hero-line">HERE<span className="dot">.</span></span></h1><div className="hero-bottom hero-line"><p>Technology is not something you watch.<br/>It’s something you step into.</p><a className="button" href="#about">DISCOVER TECHFEST <span>↓</span></a></div></div><div className="scroll-cue">SCROLL TO EXPLORE <span>↓</span></div></section>
<section id="about" className="about section"><div className="section-label">01 / ABOUT</div><div className="about-grid"><h2 className="reveal">A festival for the <em>curious.</em><br/>A launchpad for the<br/><strong>bold.</strong></h2><div className="about-copy reveal"><p>Techfest is Asia’s largest science and technology festival — a living collision of ideas, people and possibility.</p><p>Every year, IIT Bombay opens its gates to the future. This is where the next chapter starts.</p><a className="text-link" href="#missions">OUR STORY <span>↗</span></a></div></div><div className="stats">{stats.map(([n,l],i)=><div className="stat reveal" key={l}><div className="stat-number" data-value={n.replace(/\D/g,'')}>{n}</div><div>{l}</div></div>)}</div></section>
<section id="missions" className="missions section dark"><div className="section-label">02 / YOUR MISSION</div><h2 className="reveal">CHOOSE YOUR<br/><span>ADVENTURE.</span></h2><div className="mission-grid">{missions.map(([no,t,d])=><article className="mission-card reveal" key={no}><span>{no}</span><h3>{t}</h3><p>{d}</p><i>↗</i></article>)}</div></section>
<section id="events" className="events section"><div className="section-label">03 / THE ARENA</div><div className="events-head"><h2 className="reveal">BUILT TO<br/><em>DISRUPT.</em></h2><p className="reveal">Competitions, workshops and experiences designed to make you think sideways.</p></div><div className="event-list">{events.map(([t,m,d],i)=><article className="event-card reveal" key={t}><div className="event-index">0{i+1}</div><div><h3>{t}</h3><p>{m}</p></div><div className="event-desc">{d}</div><span className="arrow">↗</span></article>)}</div></section>
<section className="campus section"><div className="campus-image"/><div className="campus-content"><div className="section-label">04 / IIT BOMBAY</div><h2 className="reveal">WHERE<br/><span>IT BEGINS.</span></h2><p className="reveal">One campus. A thousand possible futures. Come find yours.</p><a className="button" href="#enter">EXPLORE THE CAMPUS <span>↗</span></a></div></section>
<section id="enter" className="final section"><div className="section-label">05 / YOUR TURN</div><h2 className="reveal">READY TO<br/><span>STEP IN?</span></h2><p className="reveal">The future is waiting. Don’t just watch it happen.</p><a className="button primary" href="#top">ENTER TECHFEST <span>↗</span></a></section></main><footer><span>TECHFEST / IIT BOMBAY</span><span>THE FUTURE IS BUILT HERE.</span><span>© 2025 — 2026</span></footer></div>}
export default App;
